name: documentation

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOCS_OUT_DIR: docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz texlive texlive-latex-extra
      - name: create output dir
        run: mkdir -p ${{ env.DOCS_OUT_DIR }}
      - name: run doxygen
        run: |
          # prepare README for nicer display of main page in Doxygen
          cat README.md | sed "s/\`c++/\`{.cpp}/" | sed "s/\`\`\`/~~~/" > README_tmp.md
          mv README_tmp.md README.md
          doxygen .github/workflows/Doxyfile
      - name: build pdf
        run: cd ${{ env.DOCS_OUT_DIR }}/latex && make && mv refman.pdf ../CSPSolverDocs.pdf && make clean
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.DOCS_OUT_DIR }}
          branch: gh-pages
          target-folder: ${{ env.DOCS_OUT_DIR }}
